services:
  db:
    build:
      context: ../../images/postgres
      args:
        CODE_VERSION: ${POSTGRES_VERSION:-latest}
        TARGET_LOCALE: ${TARGET_LOCALE:-en_US}
        TARGET_ENCODING: ${TARGET_ENCODING:-UTF-8}
    container_name: db
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: ${POSTGRES_CPU_LIMIT:-2}
          memory: ${POSTGRES_MEMORY_LIMIT:-4G}
        reservations:
          memory: ${POSTGRES_MEMORY_RESERVE:-4G}
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?required POSTGRES_PASSWORD}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - postgres_data:${POSTGRES_DATA_PATH:?required POSTGRES_DATA_PATH}
    ports:
      - 5432:5432
    networks:
      - shared-infra-network

networks:
  shared-infra-network:
    name: shared-infra-network
    driver: bridge

volumes:
  postgres_data:
